[versions]
spring-boot = "4.1.1"
archunit = "1.5.1"
spring-modulith = "2.1.1"

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
archunit = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
spring-modulith-bom = { module = "org.springframework.modulith:spring-modulith-bom", version.ref = "spring-modulith" }
[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
